### ISSUE TITLE
multi_render.py fails to run

### ISSUE THREAD

**Issue by thegreatestminer** [andrew12/osr-stuff#1]
Python gives this error when issuing this command:
python multi_render.py notitle

```
Traceback (most recent call last):
  File "multi_image.py", line 7, in <module>
    import PIL.Image
ImportError: No module named 'PIL'
```

The beatmap and replays are in the "notitle" folder.

This is on Windows 8.1 with Python 3.5.2

EDIT: I tried doing "pip install image" and now it gives a different error:
```
Traceback (most recent call last):
  File "multi_image.py", line 124, in <module>
    im.save(os.path.join('out', '%s-%05d.png' % (basename, frame)))
  File "C:\Program Files\Python35-32\lib\site-packages\PIL\Image.py", line 1682,
 in save
    fp = builtins.open(filename, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'out\\notitle-00000.png'
```

**Comment by jonese1234** [comment]
The program does not use the multi_image.py so idk why it should matter

**Comment by thegreatestminer** [comment]
OK, I'm an idiot.

I copied the contents of the beatmap and the replays into just one folder when it supposed to be like this:
```
foobar/beatmap/contents_of_beatmap_goes_here
foobar/replays go here
```

Anyways, now it runs, then closes with the error:
```
Traceback (most recent call last):
  File "multi_render.py", line 63, in <module>
    pygame.mixer.music.load(*glob(join(pathname, '*.mp3')))
TypeError: function takes exactly 1 argument (0 given)
```

Anyway to fix this?

**Comment by thegreatestminer** [comment]
OK, I am an idiot beyond idiocy.

You just need the song and the replays in one folder, not the whole beatmap :P

What the directory is ***ACTUALLY*** supposed to look like:
```
<osu beatmap song>.mp3
replay.osr
```

closed lol

**Comment by andrew12** [comment]
hahaha. the way i have it find the mp3 kind of sucks but it worked at the time. my folders are like songs/ooi/*.osr and there's also songs/ooi/ooi.mp3

**Comment by jonese1234** [comment]
@andrew12 You know your music and the actual music ingame do not line up. they are out quite a bit it seems, takes a little editing to line them up!

Also thoughts on this : https://www.youtube.com/watch?v=nNZQY8zB-08

**Comment by andrew12** [comment]
@jonese1234 I think that's because the song doesn't start immediately in the game, but i'm not sure. it looks fine in my player :p 
also it's cool that you got it working and already made something with it :)
