### ISSUE TITLE
Replay Survival Mode

### ISSUE THREAD

**Issue by jonese1234** [andrew12/osr-stuff#7]
The idea is that you start with 50 or 100 replays and when the replay drops, they are removed from the video and so with really hard maps, you end up with only a few who are able to Fc.

This is just a thought.

**Comment by andrew12** [comment]
#4 would need to be resolved before this can be done since there's no information in the replay file about when they miss

**Comment by andrew12** [comment]
I’m closing this because it seems like some other people have already started doing this on youtube
