### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by newtoniorock8** [andrew12/osr-stuff#8]
Hello there!
So yea, I'd like to test this program, but i'm getting a ImportError on the File "multi_render.py", line 3.
It says " ImportError: No module named 'recordclass' " Hope it'll be fix soon! Thanks!

btw, I'm new to python and I don't know how to fix this one >.<

**Comment by andrew12** [comment]
Hi, I added a new package last night that you need to install. You should be able to install it with pip install recordclass.

**Comment by newtoniorock8** [comment]
Cool thanks! It is working now :)
